language: r
sudo: false
dist: trusty 
cache: 
    packages: yes
    directories: 
       - $HOME/bin

branches:
  only:
    - master

cache:

before_script:
  - Rscript -e 'blogdown::install_hugo()'

script:
  - Rscript -e 'blogdown::build_site()'

deploy:
  provider: pages
  skip_cleanup: true
  keep-history: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: public
  fqdn: anpefi.eu
  repo: anpefi/anpefi.github.io
  target_branch: master